REPORT_BLANK_MESSAGE = "[//]: # (Paste the report generated by the LLM here and make final edits as needed)"
MEMO_BLANK_MESSAGE = "[//]: # (Please write any notes in free format that can be used for weekly report prompt generation.)"
